package controller;
import java.util.*;
import model.*;
import beans.*;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class for Servlet: CompanyListServlet
 *
 */
 public class CompanyListServlet extends javax.servlet.http.HttpServlet implements javax.servlet.Servlet {
   static final long serialVersionUID = 1L;
   
    /* (non-Java-doc)
	 * @see javax.servlet.http.HttpServlet#HttpServlet()
	 */
	public CompanyListServlet() {
		super();
	   	}   	
	
	/* (non-Java-doc)
	 * @see javax.servlet.http.HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Autogenerated method stub
	    companies(request,response);
	}  	
	
	/* (non-Java-doc)
	 * @see javax.servlet.http.HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
         companies(request,response);
	}
	
	public List companies(HttpServletRequest request, HttpServletResponse response){
ArrayList companies=new ArrayList();
		try{
		
	List topics=DAO.getCompanies();
		
	int i=1;
	for(Object obj:topics){
	AddCompany t=(AddCompany)obj;	
		i++;
		
		
		t.getCname();
	companies.add(t);
	}
		}
		catch(Exception e){
		}
		return companies;
		}
	
	}
	
	
 
	
	
	
	
	
	
	

 
 
 
 